# Changes here will be overwritten by Copier.
_commit: 1.11.2
_src_path: https://github.com/pawamoy/copier-uv.git
author_email: pierre@marijon.fr
author_fullname: Pierre Marijon
author_username: natir
copyright_date: '2025'
copyright_holder: Pierre Marijon
copyright_holder_email: pierre@marijon.fr
copyright_license: MIT
project_description: Variant Knowledge Dashboard
project_name: vkd
python_package_command_line_name: vkd
python_package_distribution_name: vkd
python_package_import_name: vkd
repository_name: vkd
repository_namespace: natir
repository_provider: github.com

